# Default values for guardrails-agent-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Hostname to a Guardrails server
guardrails:
  hostname: ""

image:
  repository: ghcr.io/turbot/guardrails-agent-kubernetes
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

# Extra environment variables to pass to the agent
extraEnv: []

# Override the namespace for the deployed resources
namespaceOverride: ""

# The name of the secret containing the enrollment secret
enrollmentSecretName: ""

# Enable persistence using Persistent Volume Claims (PVCs)
persistence:
  # Enable persistence on osquery.db using a PVC. If false, use emptyDir
  enabled: true
  # The capacity of the persistent volume
  capacity: "10Gi"
  # The access modes of the persistent volume
  accessModes: [ReadWriteOnce]
  # The storage class of the persistent volume
  storageClassName: ""
  # Annotations to add to the persistent volume
  annotations: {}
  # The selector for the persistent volume
  selector: {}
  # The name of the persistent volume to use
  volumeName: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  # If not set and create is true, a name is generated using the fullname template
  name: ""

statefulSet:
  annotations: {}

role:
  annotations: {}

roleBinding:
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

containerSecurityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 2000
  allowPrivilegeEscalation: false

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output StatefulSet definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output StatefulSet definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
