apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardrails:lister-binding
  namespace: {{ include "guardrails-agent-kubernetes.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "guardrails-agent-kubernetes.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: guardrails:lister
  apiGroup: rbac.authorization.k8s.io
