apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardrails:agent:lister
  labels:
    {{- include "guardrails-agent-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "guardrails-agent-kubernetes.serviceAccountName" . }}
    namespace: {{ include "guardrails-agent-kubernetes.namespace" . }}
roleRef:
  kind: ClusterRole
  name: guardrails:lister
  apiGroup: rbac.authorization.k8s.io
