apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardrails:lister-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "guardrails-k8s-agent.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: guardrails:lister
  apiGroup: rbac.authorization.k8s.io
