apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardrails:lister
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - secrets
      - services
      - serviceaccounts
    verbs: ["list"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["list"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingress
      - networkpolicies
    verbs: ["list"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs: ["list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["list"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["list"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["list"]
