{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guardrails-agent-kubernetes.serviceAccountName" . }}
  labels:
    {{- include "guardrails-agent-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "guardrails-agent-kubernetes.namespace" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
