apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "guardrails-agent-kubernetes.fullname" . }}
  labels:
    {{- include "guardrails-agent-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.statefulSet.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "guardrails-agent-kubernetes.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "guardrails-agent-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "guardrails-agent-kubernetes.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "guardrails-agent-kubernetes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOSTNAME
              value: {{ .Values.guardrails.hostname }}
            - name: ENROLL_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.enrollmentSecretName | default "guardrails-agent-kubernetes-secret" }}
                  key: enroll-secret
            {{- if .Values.extraEnv }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- end }}
              {{- if .valueFrom }}
              valueFrom:
                {{- if .valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: osquery-data 
              mountPath: /var/osquery/
            - name: temp-directory
              mountPath: /tmp/
            - name: osquery-socket
              mountPath: /var/osquery
      volumes:
        - name: temp-directory
          emptyDir: {}
        - name: osquery-socket
          emptyDir: {}
        - name: osquery-data
          {{- if .Values.persistence.enabled }}
          persistenceVolumeClaim:
            claimName: {{ include "guardrails-agent-kubernetes.fullname" . }}
          {{- else }}
          emptyDir:
            sizeLimit: {{ .Values.persistence.capacity }}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
