{{- if .Values.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "guardrails-agent-kubernetes.fullname" . }}
  labels:
    {{- include "guardrails-agent-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.persistentVolume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "guardrails-agent-kubernetes.namespace" . }}
spec:
  accessModes: {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.capacity }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  {{- if .Values.persistentVolume.selector }}
  selector:
    {{- toYaml .Values.persistentVolume.selector | nindent 4 }}
  {{- end }}
  {{- if .Values.persistentVolume.volumeName }}
  volumeName: "{{ .Values.persistentVolume.volumeName }}"
  {{- end -}}
{{- end }}
