{{- if .Values.persistentVolumeClaim.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "guardrails-agent-kubernetes.persistentVolumeClaimName" . }}
  labels:
    {{- include "guardrails-agent-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.persistentVolumeClaim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "guardrails-agent-kubernetes.namespace" . }}
spec:
  accessModes: {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.capacity }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
