name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

# Prevent two release workflows from running concurrently, which might cause write-after-read race conditions in the repository's gh-pages branch
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency: helm-release

jobs:
  release-charts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  sync-readme:
    needs: release-charts
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit --signoff -m "Sync README from main" && git push)
